const { DataTypes, Model } = require('sequelize');
const database = require('../config/database');

class Order extends Model {}

Order.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  restaurant_id: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  customer_id: {
    type: DataTypes.INTEGER,
    allowNull: true,
    comment: 'Customer ID for logged-in users'
  },
  order_number: {
    type: DataTypes.STRING(50),
    allowNull: true  // Generated by backend, can be null temporarily during creation
  },
  customer_name: {
    type: DataTypes.STRING(255),
    allowNull: true
  },
  customer_phone: {
    type: DataTypes.STRING(50),
    allowNull: true
  },
  table_number: {
    type: DataTypes.STRING(10),
    allowNull: true
  },
  floor_plan_table_id: {
    type: DataTypes.STRING(64),
    allowNull: true,
    comment: 'Floor plan v2 tables[].id (e.g. "t_abc123"). Disambiguates same table_number across different zones. NULL for legacy orders (pre-2026-05-27).'
  },
  table_cleared: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment: '2026-05-31: "Leave/Clear table" frees the table on the floor plan WITHOUT erasing table_number. Was previously done by nulling table_number, which destroyed the order history ("Dine-in · no table assigned"). table-status excludes table_cleared=true from occupancy; the order keeps its table_number for bills/reports/today-history.'
  },
  guest_count: {
    type: DataTypes.INTEGER,
    allowNull: true,
    defaultValue: null,
    comment: 'Number of guests at the table (dine-in only)'
  },
  pager_number: {
    type: DataTypes.STRING(10),
    allowNull: true,
    comment: 'Pager device number for order notification'
  },
  total_amount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false
  },
  status: {
    type: DataTypes.ENUM('awaiting_payment', 'pending', 'preparing', 'ready', 'served', 'completed', 'cancelled', 'outstanding'),
    defaultValue: 'awaiting_payment'
  },
  // 2026-05-28 매장 critical: source 무관 (POS/모바일/FloorPlan) 주문 발생 직후
  // backend 가 set, 매장 device 가 polling 으로 catch → 인쇄 후 false set.
  // Frontend socket 의존성을 제거. backend 가 단일 진실.
  needs_print: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'Pending kitchen auto-print flag. Set true on Order.create. Cleared by frontend.'
  },
  // 2026-06-24: print-claim 자동복구. 어느 기기가 print-claim(needs_print→false) 하면 NOW 기록.
  // /printed(인쇄확인)·/print-rearm·/print-dismiss 시 NULL. pending-print 조회 시 NOT NULL 이면서
  // STALE(>STALE_CLAIM_SEC) 이면 = 인쇄확인이 안 온 죽은 claim → 자동 re-arm(needs_print=true) 해
  // 인쇄 전담 POS 가 받게 한다. 불변식: print_claimed_at NOT NULL ⟺ "claim됐으나 인쇄 미확인".
  // 기기 설정 무관·분실 0. (docs/PRINT_DB_DRIVEN_DISPATCH.md)
  print_claimed_at: {
    type: DataTypes.DATE,
    allowNull: true,
    defaultValue: null,
    comment: 'When a device print-claimed this order (cleared on /printed). Stale = auto re-armed.'
  },
  // 2026-06-24: 테이블이동·취소·void 재인쇄도 "누른 기기 직접인쇄" → "DB → 인쇄 전담 POS 폴러"로 통일.
  // pending_reprint = { type:'move'|'cancel'|'void', data:{...인쇄데이터 스냅샷} }. 액션 라우트가 설정,
  // 폴러가 type 에 맞는 기존 인쇄함수 호출 후 NULL. reprint_claimed_at = print_claimed_at 와 동일한
  // 죽은-claim 자동복구. 누가/어느 기기/어느 계정으로 했든 인쇄 전담 POS 가 인쇄. (PRINT_DB_DRIVEN_DISPATCH)
  pending_reprint: {
    type: DataTypes.JSON,
    allowNull: true,
    defaultValue: null,
    comment: 'Queued reprint job {type, data} for table-move/cancel/void. POS poller prints + clears.'
  },
  reprint_claimed_at: {
    type: DataTypes.DATE,
    allowNull: true,
    defaultValue: null,
    comment: 'When a device claimed the pending_reprint (cleared on done). Stale = auto re-armed.'
  },
  // 2026-05-28: needs_bill — separate flag for cashier bill receipt auto-print.
  // Set true on merge (mobile 같은 테이블 추가 = staff 주문관리용 누적 영수증).
  // Single new orders 는 false (결제 버튼 시점에만 bill 인쇄).
  needs_bill: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'Pending bill auto-print flag. Set true on merge (mobile 같은 테이블 추가).'
  },
  // 2026-06-09: consolidated_printed_at — independent print-state for the optional
  // "Consolidated Order Ticket" (whole order on one ticket to a configurable printer,
  // e.g. a kitchen main printer). Tracked separately from per-item printed_at so the
  // consolidated-ticket poller never interferes with the station/kitchen print cycle.
  // NULL = not yet consolidated-printed. Stamped by PATCH /consolidated-print/:id/printed.
  consolidated_printed_at: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'When the optional consolidated order ticket was printed (independent of needs_print).'
  },
  order_type: {
    type: DataTypes.ENUM('dine_in', 'takeaway', 'delivery', 'pickup', 'reservation_deposit'),
    defaultValue: 'dine_in'
  },
  reservation_id: {
    type: DataTypes.INTEGER,
    allowNull: true,
    references: { model: 'reservations', key: 'id' },
    comment: 'FK to Reservation when this order is a deposit prepayment or a reservation-attached order'
  },
  source: {
    type: DataTypes.ENUM('pos', 'mobile', 'kiosk'),
    defaultValue: 'pos',
    comment: 'Order source: pos (POS Terminal), mobile (Mobile Order), kiosk (Self-service Kiosk)'
  },
  payment_method: {
    type: DataTypes.STRING(50),
    allowNull: true
  },
  card_type: {
    type: DataTypes.STRING(20),
    allowNull: true,
    comment: 'Card type when payment_method is card: visa, master, amex, other'
  },
  payment_status: {
    type: DataTypes.ENUM('pending', 'partial', 'completed', 'failed', 'payment_verification_pending', 'rejected'),
    defaultValue: 'pending'
  },
  // Split bill 누적 결제액. amount_paid >= total_amount 이면 payment_status='completed'.
  amount_paid: {
    type: DataTypes.DECIMAL(10, 2),
    defaultValue: 0,
    allowNull: false
  },
  payment_intent_id: {
    type: DataTypes.STRING(255),
    allowNull: true,
    comment: 'Stripe PaymentIntent ID or PayPal Order ID for online payments'
  },
  payment_provider: {
    type: DataTypes.STRING(20),
    allowNull: true,
    comment: 'Payment provider: stripe, paypal'
  },
  transaction_id: {
    type: DataTypes.STRING(255),
    allowNull: true,
    comment: 'Payment transaction ID from provider'
  },
  kitchen_ready: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'True when payment is completed OR Proceed Without Payment is clicked'
  },
  order_date: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW
  },
  order_items: {
    type: DataTypes.TEXT,
    allowNull: true,
    get() {
      const value = this.getDataValue('order_items');
      return value ? JSON.parse(value) : null;
    },
    set(value) {
      this.setDataValue('order_items', value ? JSON.stringify(value) : null);
    }
  },
  payment_proof: {
    type: DataTypes.TEXT('long'),
    allowNull: true,
    get() {
      const value = this.getDataValue('payment_proof');
      return value ? JSON.parse(value) : null;
    },
    set(value) {
      this.setDataValue('payment_proof', value ? JSON.stringify(value) : null);
    }
  },
  subtotal: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    comment: 'Subtotal before tax and service charge'
  },
  tax: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Tax amount'
  },
  tax_rate: {
    type: DataTypes.DECIMAL(5, 2),
    allowNull: true,
    defaultValue: 6,
    comment: 'Tax rate percentage'
  },
  service_charge: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Service charge amount'
  },
  service_charge_rate: {
    type: DataTypes.DECIMAL(5, 2),
    allowNull: true,
    defaultValue: 10,
    comment: 'Service charge rate percentage'
  },
  discount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Fixed discount amount'
  },
  discount_policy_name: {
    type: DataTypes.STRING(50),
    allowNull: true,
    comment: 'Discount policy name (e.g., "20%", "Staff", "VIP")'
  },
  discount_policy_amount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Percentage-based discount policy amount'
  },
  coupon_code: {
    type: DataTypes.STRING(50),
    allowNull: true,
    comment: 'Coupon code applied'
  },
  coupon_discount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Coupon discount amount'
  },
  takeaway_charge: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Takeaway charge amount'
  },
  served_at: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Timestamp when order status changed to served'
  },
  scheduled_pickup_time: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Scheduled pickup time for pre-order pickup'
  },
  delivery_info: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Delivery information (address, phone, notes, zone)',
    get() {
      const value = this.getDataValue('delivery_info');
      return value ? JSON.parse(value) : null;
    },
    set(value) {
      this.setDataValue('delivery_info', value ? JSON.stringify(value) : null);
    }
  },
  delivery_fee: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Delivery fee amount'
  },
  points_used: {
    type: DataTypes.INTEGER,
    allowNull: true,
    defaultValue: 0,
    comment: 'Points used for this order'
  },
  point_discount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Discount amount from points usage'
  },
  cashier_id: {
    type: DataTypes.INTEGER,
    allowNull: true,
    comment: 'Staff who processed this order (POS cashier)'
  },
  cashier_name: {
    type: DataTypes.STRING(255),
    allowNull: true,
    comment: 'Cashier name snapshot (preserved after staff changes)'
  },
  is_deleted: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment: 'Soft delete flag - order number is preserved'
  },
  deleted_at: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Timestamp when order was soft deleted'
  }
}, {
  sequelize: database.sequelize,
  modelName: 'Order',
  tableName: 'orders',
  timestamps: true
});

module.exports = Order;
