const { DataTypes, Model } = require('sequelize');
const database = require('../config/database');

class Order extends Model {}

Order.init({
  id: {
    type: DataTypes.INTEGER,
    primaryKey: true,
    autoIncrement: true
  },
  restaurant_id: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  customer_id: {
    type: DataTypes.INTEGER,
    allowNull: true,
    comment: 'Customer ID for logged-in users'
  },
  order_number: {
    type: DataTypes.STRING(50),
    allowNull: true  // Generated by backend, can be null temporarily during creation
  },
  customer_name: {
    type: DataTypes.STRING(255),
    allowNull: true
  },
  customer_phone: {
    type: DataTypes.STRING(50),
    allowNull: true
  },
  table_number: {
    type: DataTypes.STRING(10),
    allowNull: true
  },
  guest_count: {
    type: DataTypes.INTEGER,
    allowNull: true,
    defaultValue: null,
    comment: 'Number of guests at the table (dine-in only)'
  },
  pager_number: {
    type: DataTypes.STRING(10),
    allowNull: true,
    comment: 'Pager device number for order notification'
  },
  total_amount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false
  },
  status: {
    type: DataTypes.ENUM('awaiting_payment', 'pending', 'preparing', 'ready', 'served', 'completed', 'cancelled', 'outstanding'),
    defaultValue: 'awaiting_payment'
  },
  order_type: {
    type: DataTypes.ENUM('dine_in', 'takeaway', 'delivery', 'pickup'),
    defaultValue: 'dine_in'
  },
  source: {
    type: DataTypes.ENUM('pos', 'mobile', 'kiosk'),
    defaultValue: 'pos',
    comment: 'Order source: pos (POS Terminal), mobile (Mobile Order), kiosk (Self-service Kiosk)'
  },
  payment_method: {
    type: DataTypes.STRING(50),
    allowNull: true
  },
  payment_status: {
    type: DataTypes.ENUM('pending', 'completed', 'failed', 'payment_verification_pending'),
    defaultValue: 'pending'
  },
  kitchen_ready: {
    type: DataTypes.BOOLEAN,
    defaultValue: false,
    comment: 'True when payment is completed OR Proceed Without Payment is clicked'
  },
  order_date: {
    type: DataTypes.DATE,
    defaultValue: DataTypes.NOW
  },
  order_items: {
    type: DataTypes.TEXT,
    allowNull: true,
    get() {
      const value = this.getDataValue('order_items');
      return value ? JSON.parse(value) : null;
    },
    set(value) {
      this.setDataValue('order_items', value ? JSON.stringify(value) : null);
    }
  },
  payment_proof: {
    type: DataTypes.TEXT('long'),
    allowNull: true,
    get() {
      const value = this.getDataValue('payment_proof');
      return value ? JSON.parse(value) : null;
    },
    set(value) {
      this.setDataValue('payment_proof', value ? JSON.stringify(value) : null);
    }
  },
  subtotal: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    comment: 'Subtotal before tax and service charge'
  },
  tax: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Tax amount'
  },
  tax_rate: {
    type: DataTypes.DECIMAL(5, 2),
    allowNull: true,
    defaultValue: 6,
    comment: 'Tax rate percentage'
  },
  service_charge: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Service charge amount'
  },
  service_charge_rate: {
    type: DataTypes.DECIMAL(5, 2),
    allowNull: true,
    defaultValue: 10,
    comment: 'Service charge rate percentage'
  },
  discount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Fixed discount amount'
  },
  discount_policy_name: {
    type: DataTypes.STRING(50),
    allowNull: true,
    comment: 'Discount policy name (e.g., "20%", "Staff", "VIP")'
  },
  discount_policy_amount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Percentage-based discount policy amount'
  },
  coupon_code: {
    type: DataTypes.STRING(50),
    allowNull: true,
    comment: 'Coupon code applied'
  },
  coupon_discount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Coupon discount amount'
  },
  takeaway_charge: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Takeaway charge amount'
  },
  served_at: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Timestamp when order status changed to served'
  },
  scheduled_pickup_time: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Scheduled pickup time for pre-order pickup'
  },
  delivery_info: {
    type: DataTypes.TEXT,
    allowNull: true,
    comment: 'Delivery information (address, phone, notes, zone)',
    get() {
      const value = this.getDataValue('delivery_info');
      return value ? JSON.parse(value) : null;
    },
    set(value) {
      this.setDataValue('delivery_info', value ? JSON.stringify(value) : null);
    }
  },
  delivery_fee: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Delivery fee amount'
  },
  points_used: {
    type: DataTypes.INTEGER,
    allowNull: true,
    defaultValue: 0,
    comment: 'Points used for this order'
  },
  point_discount: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: true,
    defaultValue: 0,
    comment: 'Discount amount from points usage'
  },
  cashier_id: {
    type: DataTypes.INTEGER,
    allowNull: true,
    comment: 'Staff who processed this order (POS cashier)'
  },
  cashier_name: {
    type: DataTypes.STRING(255),
    allowNull: true,
    comment: 'Cashier name snapshot (preserved after staff changes)'
  },
  is_deleted: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    comment: 'Soft delete flag - order number is preserved'
  },
  deleted_at: {
    type: DataTypes.DATE,
    allowNull: true,
    comment: 'Timestamp when order was soft deleted'
  }
}, {
  sequelize: database.sequelize,
  modelName: 'Order',
  tableName: 'orders',
  timestamps: true
});

module.exports = Order;
